///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddSampleTypeClick recording.
    /// </summary>
    [TestModule("09eaa260-f8c6-4a2c-a43e-e858df44de9f", ModuleType.Recording, 1)]
    public partial class AddSampleTypeClick : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysDesktopExplorerRepository repository.
        /// </summary>
        public static MyAssaysDesktopExplorerRepository repo = MyAssaysDesktopExplorerRepository.Instance;

        static AddSampleTypeClick instance = new AddSampleTypeClick();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddSampleTypeClick()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddSampleTypeClick Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.AddSampleType' at 99;8.", repo.SampleTypesEditor.SomeContainer2.AddSampleTypeInfo, new RecordItemIndex(0));
            repo.SampleTypesEditor.SomeContainer2.AddSampleType.Click("99;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.SomeElement1' at 112;7.", repo.SampleTypesEditor.SomeContainer2.SomeElement1Info, new RecordItemIndex(1));
            repo.SampleTypesEditor.SomeContainer2.SomeElement1.Click("112;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 19}'.", new RecordItemIndex(2));
            Keyboard.Press("{Back 19}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}o{LShiftKey up}ne'.", new RecordItemIndex(3));
            Keyboard.Press("{LShiftKey down}o{LShiftKey up}ne");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.ButtonOK' at 14;9.", repo.SampleTypesEditor.SomeContainer2.ButtonOKInfo, new RecordItemIndex(4));
            repo.SampleTypesEditor.SomeContainer2.ButtonOK.Click("14;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Select the sample types used in your assay:') on item 'NewProtocolWizard.SomeContainer2.SelectTheSampleTypesUsedInYourAss'.", repo.NewProtocolWizard.SomeContainer2.SelectTheSampleTypesUsedInYourAssInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SelectTheSampleTypesUsedInYourAssInfo, "Text", "Select the sample types used in your assay:");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
