///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddSampleType recording.
    /// </summary>
    [TestModule("de77c48c-f92c-4965-a4e5-21bcb519fe7e", ModuleType.Recording, 1)]
    public partial class AddSampleType : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysDesktopExplorerRepository repository.
        /// </summary>
        public static MyAssaysDesktopExplorerRepository repo = MyAssaysDesktopExplorerRepository.Instance;

        static AddSampleType instance = new AddSampleType();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddSampleType()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddSampleType Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.AddSampleType' at 60;9.", repo.SampleTypesEditor.SomeContainer2.AddSampleTypeInfo, new RecordItemIndex(0));
            repo.SampleTypesEditor.SomeContainer2.AddSampleType.Click("60;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.ToggleButton' at 155;13.", repo.SampleTypesEditor.ToggleButtonInfo, new RecordItemIndex(1));
            repo.SampleTypesEditor.ToggleButton.Click("155;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Calibrator' at 103;10.", repo.MyAssaysDesktopExplorer.CalibratorInfo, new RecordItemIndex(2));
            repo.MyAssaysDesktopExplorer.Calibrator.Click("103;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.SomeContainer' at 151;16.", repo.SampleTypesEditor.SomeContainer2.SomeContainerInfo, new RecordItemIndex(3));
            repo.SampleTypesEditor.SomeContainer2.SomeContainer.Click("151;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.SomeContainer' at 65;65.", repo.MyAssaysDesktopExplorer.SomeContainerInfo, new RecordItemIndex(4));
            repo.MyAssaysDesktopExplorer.SomeContainer.Click("65;65");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.SomeButton' at 12;35.", repo.MyAssaysDesktopExplorer.SomeButtonInfo, new RecordItemIndex(5));
            repo.MyAssaysDesktopExplorer.SomeButton.Click("12;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.SomeButton' at 16;19.", repo.MyAssaysDesktopExplorer.SomeButtonInfo, new RecordItemIndex(6));
            repo.MyAssaysDesktopExplorer.SomeButton.Click("16;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.SomeElement' at 155;14.", repo.SampleTypesEditor.SomeContainer2.SomeElementInfo, new RecordItemIndex(7));
            repo.SampleTypesEditor.SomeContainer2.SomeElement.Click("155;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SampleTypesEditor.SomeContainer2.SomeElement' at 82;11.", repo.SampleTypesEditor.SomeContainer2.SomeElementInfo, new RecordItemIndex(8));
            repo.SampleTypesEditor.SomeContainer2.SomeElement.MoveTo("82;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SampleTypesEditor.SomeContainer2.SomeElement' at 90;3.", repo.SampleTypesEditor.SomeContainer2.SomeElementInfo, new RecordItemIndex(9));
            repo.SampleTypesEditor.SomeContainer2.SomeElement.MoveTo("90;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MyAssaysExplorer.SomeContainer1.SomeContainer' at 10;197.", repo.MyAssaysExplorer.SomeContainer1.SomeContainerInfo, new RecordItemIndex(10));
            repo.MyAssaysExplorer.SomeContainer1.SomeContainer.MoveTo("10;197");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{LShiftKey down}o{LShiftKey up}ne'.", new RecordItemIndex(11));
            Keyboard.Press("{Back}{LShiftKey down}o{LShiftKey up}ne");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1' at 407;393.", repo.SampleTypesEditor.SomeContainer1Info, new RecordItemIndex(12));
            repo.SampleTypesEditor.SomeContainer1.Click("407;393");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer2.ButtonOK' at 27;15.", repo.SampleTypesEditor.SomeContainer2.ButtonOKInfo, new RecordItemIndex(13));
            repo.SampleTypesEditor.SomeContainer2.ButtonOK.Click("27;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
