///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create recording.
    /// </summary>
    [TestModule("99faa354-6348-40e1-82cf-f6e35fd763bf", ModuleType.Recording, 1)]
    public partial class Create : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysDesktopExplorerRepository repository.
        /// </summary>
        public static MyAssaysDesktopExplorerRepository repo = MyAssaysDesktopExplorerRepository.Instance;

        static Create instance = new Create();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer' at 63;0.", repo.NewProtocolWizard.SomeContainerInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer.Click("63;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.ListView' at 80;4.", repo.MyAssaysDesktopExplorer.ListViewInfo, new RecordItemIndex(1));
            repo.MyAssaysDesktopExplorer.ListView.Click("80;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.TEXT12' at 20;13.", repo.LayoutEditor.PARTElementPlateGrid.TEXT12Info, new RecordItemIndex(2));
            repo.LayoutEditor.PARTElementPlateGrid.TEXT12.Click("20;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.TEXT13' at 11;20.", repo.LayoutEditor.PARTElementPlateGrid.TEXT13Info, new RecordItemIndex(3));
            repo.LayoutEditor.PARTElementPlateGrid.TEXT13.Click("11;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 47;37.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(4));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("47;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 113;38.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(5));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("113;38");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.TEXT2' at 11;15.", repo.LayoutEditor.PARTElementPlateGrid.TEXT2Info, new RecordItemIndex(6));
            repo.LayoutEditor.PARTElementPlateGrid.TEXT2.Click("11;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.TEXT3' at 0;16.", repo.LayoutEditor.PARTElementPlateGrid.TEXT3Info, new RecordItemIndex(7));
            repo.LayoutEditor.PARTElementPlateGrid.TEXT3.Click("0;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 292;40.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(8));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("292;40");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.TEXT5' at 3;18.", repo.LayoutEditor.PARTElementPlateGrid.TEXT5Info, new RecordItemIndex(9));
            repo.LayoutEditor.PARTElementPlateGrid.TEXT5.Click("3;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 419;29.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(10));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("419;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 485;33.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(11));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("485;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 534;49.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(12));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("534;49");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 590;18.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(13));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("590;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 648;35.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(14));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("648;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 705;37.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(15));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("705;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTImage' at 17;30.", repo.LayoutEditor.PARTImageInfo, new RecordItemIndex(16));
            repo.LayoutEditor.PARTImage.Click("17;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 22;11.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(17));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("22;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 23;10.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(18));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("23;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Name your protocol and optionally provide a description.') on item 'NewProtocolWizard.SomeContainer2.NameYourProtocolAndOptionallyProvid'.", repo.NewProtocolWizard.SomeContainer2.NameYourProtocolAndOptionallyProvidInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.NameYourProtocolAndOptionallyProvidInfo, "Text", "Name your protocol and optionally provide a description.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
