///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DescriptionAndValidate recording.
    /// </summary>
    [TestModule("960fb826-87e5-481b-babe-c05192363b1a", ModuleType.Recording, 1)]
    public partial class DescriptionAndValidate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysDesktopExplorerRepository repository.
        /// </summary>
        public static MyAssaysDesktopExplorerRepository repo = MyAssaysDesktopExplorerRepository.Instance;

        static DescriptionAndValidate instance = new DescriptionAndValidate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DescriptionAndValidate()
        {
            Description = "Dual Endpont and Counts";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DescriptionAndValidate Instance
        {
            get { return instance; }
        }

#region Variables

        string _Description;

        /// <summary>
        /// Gets or sets the value of variable Description.
        /// </summary>
        [TestVariable("a7f7971f-a719-4baa-ac03-cd5b9e060d26")]
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Click item 'NewProtocolWizard.SomeContainer2.SomeElement' at 74;19.", repo.NewProtocolWizard.SomeContainer2.SomeElementInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.SomeElement.Click(System.Windows.Forms.MouseButtons.None, "74;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Description'.", new RecordItemIndex(1));
            Keyboard.Press(Description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at Center.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Review the configuration summary; press Finish to create the protocol.') on item 'NewProtocolWizard.SomeContainer2.ReviewTheConfigurationSummaryPress'.", repo.NewProtocolWizard.SomeContainer2.ReviewTheConfigurationSummaryPressInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.ReviewTheConfigurationSummaryPressInfo, "Text", "Review the configuration summary; press Finish to create the protocol.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
