///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MeasAndTechnol_Format_ManageTypes recording.
    /// </summary>
    [TestModule("b6afc49a-c0dc-41ae-a4e1-0aa421227741", ModuleType.Recording, 1)]
    public partial class MeasAndTechnol_Format_ManageTypes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysDesktopExplorerRepository repository.
        /// </summary>
        public static MyAssaysDesktopExplorerRepository repo = MyAssaysDesktopExplorerRepository.Instance;

        static MeasAndTechnol_Format_ManageTypes instance = new MeasAndTechnol_Format_ManageTypes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MeasAndTechnol_Format_ManageTypes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MeasAndTechnol_Format_ManageTypes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList' at 102;110.", repo.NewProtocolWizard.SomeContainer2.SomeListInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.SomeList.Click("102;110");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList1' at 121;42.", repo.NewProtocolWizard.SomeContainer2.SomeList1Info, new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer2.SomeList1.Click("121;42");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 16;11.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList2' at 80;93.", repo.NewProtocolWizard.SomeContainer2.SomeList2Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer2.SomeList2.Click("80;93");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 19;3.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("19;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.AdvancedViewButton' at 32;14.", repo.NewProtocolWizard.SomeContainer2.AdvancedViewButtonInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.SomeContainer2.AdvancedViewButton.Click("32;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Edit the sample types used in your assays. Press OK to save changes.') on item 'SampleTypesEditor.SomeContainer2.EditTheSampleTypesUsedInYourAssay'.", repo.SampleTypesEditor.SomeContainer2.EditTheSampleTypesUsedInYourAssayInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer2.EditTheSampleTypesUsedInYourAssayInfo, "Text", "Edit the sample types used in your assays. Press OK to save changes.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
