///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyAssaysDesktopExplorer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyAssaysDesktopExplorerRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("b9421caf-34ef-41da-99ff-a67eb9dcd081")]
    public partial class MyAssaysDesktopExplorerRepository : RepoGenBaseFolder
    {
        static MyAssaysDesktopExplorerRepository instance = new MyAssaysDesktopExplorerRepository();
        MyAssaysDesktopExplorerRepositoryFolders.MyAssaysExplorerAppFolder _myassaysexplorer;
        MyAssaysDesktopExplorerRepositoryFolders.NewProtocolWizardAppFolder _newprotocolwizard;
        MyAssaysDesktopExplorerRepositoryFolders.SampleTypesEditorAppFolder _sampletypeseditor;
        MyAssaysDesktopExplorerRepositoryFolders.MyAssaysDesktopExplorerAppFolder _myassaysdesktopexplorer;
        MyAssaysDesktopExplorerRepositoryFolders.LayoutEditorAppFolder _layouteditor;

        /// <summary>
        /// Gets the singleton class instance representing the MyAssaysDesktopExplorerRepository element repository.
        /// </summary>
        [RepositoryFolder("b9421caf-34ef-41da-99ff-a67eb9dcd081")]
        public static MyAssaysDesktopExplorerRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyAssaysDesktopExplorerRepository() 
            : base("MyAssaysDesktopExplorerRepository", "/", null, 0, false, "b9421caf-34ef-41da-99ff-a67eb9dcd081", ".\\RepositoryImages\\MyAssaysDesktopExplorerRepositoryb9421caf.rximgres")
        {
            _myassaysexplorer = new MyAssaysDesktopExplorerRepositoryFolders.MyAssaysExplorerAppFolder(this);
            _newprotocolwizard = new MyAssaysDesktopExplorerRepositoryFolders.NewProtocolWizardAppFolder(this);
            _sampletypeseditor = new MyAssaysDesktopExplorerRepositoryFolders.SampleTypesEditorAppFolder(this);
            _myassaysdesktopexplorer = new MyAssaysDesktopExplorerRepositoryFolders.MyAssaysDesktopExplorerAppFolder(this);
            _layouteditor = new MyAssaysDesktopExplorerRepositoryFolders.LayoutEditorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b9421caf-34ef-41da-99ff-a67eb9dcd081")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyAssaysExplorer folder.
        /// </summary>
        [RepositoryFolder("ba9ac6b0-d589-4921-a048-0ca8ddcc72ce")]
        public virtual MyAssaysDesktopExplorerRepositoryFolders.MyAssaysExplorerAppFolder MyAssaysExplorer
        {
            get { return _myassaysexplorer; }
        }

        /// <summary>
        /// The NewProtocolWizard folder.
        /// </summary>
        [RepositoryFolder("2919cf15-927b-4a31-99f3-f4f743525167")]
        public virtual MyAssaysDesktopExplorerRepositoryFolders.NewProtocolWizardAppFolder NewProtocolWizard
        {
            get { return _newprotocolwizard; }
        }

        /// <summary>
        /// The SampleTypesEditor folder.
        /// </summary>
        [RepositoryFolder("73c552ed-057f-4e5d-b263-ea1a497edb57")]
        public virtual MyAssaysDesktopExplorerRepositoryFolders.SampleTypesEditorAppFolder SampleTypesEditor
        {
            get { return _sampletypeseditor; }
        }

        /// <summary>
        /// The MyAssaysDesktopExplorer folder.
        /// </summary>
        [RepositoryFolder("7ad59ab9-a199-46e3-99d6-597e5ab45eae")]
        public virtual MyAssaysDesktopExplorerRepositoryFolders.MyAssaysDesktopExplorerAppFolder MyAssaysDesktopExplorer
        {
            get { return _myassaysdesktopexplorer; }
        }

        /// <summary>
        /// The LayoutEditor folder.
        /// </summary>
        [RepositoryFolder("03f04b93-4edc-41a9-9a2e-753335eeaa1f")]
        public virtual MyAssaysDesktopExplorerRepositoryFolders.LayoutEditorAppFolder LayoutEditor
        {
            get { return _layouteditor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class MyAssaysDesktopExplorerRepositoryFolders
    {
        /// <summary>
        /// The MyAssaysExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("ba9ac6b0-d589-4921-a048-0ca8ddcc72ce")]
        public partial class MyAssaysExplorerAppFolder : RepoGenBaseFolder
        {
            MyAssaysDesktopExplorerRepositoryFolders.SomeContainer1Folder _somecontainer1;
            RepoItemInfo _blurrectInfo;
            RepoItemInfo _rightblurrectInfo;

            /// <summary>
            /// Creates a new MyAssaysExplorer  folder.
            /// </summary>
            public MyAssaysExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyAssaysExplorer", "/form[@wpfnative='True' and @title='MyAssays Explorer' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 30000, null, true, "ba9ac6b0-d589-4921-a048-0ca8ddcc72ce", "")
            {
                _somecontainer1 = new MyAssaysDesktopExplorerRepositoryFolders.SomeContainer1Folder(this);
                _blurrectInfo = new RepoItemInfo(this, "BlurRect", ".//container[@automationid='GlassActive']/element[@automationid='BlurRect']", 30000, null, "37f116b5-0f24-4c33-9a36-ad6d74f5c6c8");
                _rightblurrectInfo = new RepoItemInfo(this, "RightBlurRect", ".//container[@automationid='GlassActive']/element[@automationid='RightBlurRect']", 30000, null, "c511df2c-5d87-435e-b092-a1b705d051d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba9ac6b0-d589-4921-a048-0ca8ddcc72ce")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba9ac6b0-d589-4921-a048-0ca8ddcc72ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BlurRect item.
            /// </summary>
            [RepositoryItem("37f116b5-0f24-4c33-9a36-ad6d74f5c6c8")]
            public virtual Ranorex.Unknown BlurRect
            {
                get
                {
                    return _blurrectInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BlurRect item info.
            /// </summary>
            [RepositoryItemInfo("37f116b5-0f24-4c33-9a36-ad6d74f5c6c8")]
            public virtual RepoItemInfo BlurRectInfo
            {
                get
                {
                    return _blurrectInfo;
                }
            }

            /// <summary>
            /// The RightBlurRect item.
            /// </summary>
            [RepositoryItem("c511df2c-5d87-435e-b092-a1b705d051d8")]
            public virtual Ranorex.Unknown RightBlurRect
            {
                get
                {
                    return _rightblurrectInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The RightBlurRect item info.
            /// </summary>
            [RepositoryItemInfo("c511df2c-5d87-435e-b092-a1b705d051d8")]
            public virtual RepoItemInfo RightBlurRectInfo
            {
                get
                {
                    return _rightblurrectInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 folder.
            /// </summary>
            [RepositoryFolder("aceaf7d9-8edb-49b8-877d-364e99925502")]
            public virtual MyAssaysDesktopExplorerRepositoryFolders.SomeContainer1Folder SomeContainer1
            {
                get { return _somecontainer1; }
            }
        }

        /// <summary>
        /// The SomeContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("aceaf7d9-8edb-49b8-877d-364e99925502")]
        public partial class SomeContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _sometextInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _ribbonInfo;

            /// <summary>
            /// Creates a new SomeContainer1  folder.
            /// </summary>
            public SomeContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer1", "container/container/container/container/container", parentFolder, 30000, null, false, "aceaf7d9-8edb-49b8-877d-364e99925502", "")
            {
                _sometextInfo = new RepoItemInfo(this, "SomeText", "container[2]/tabpagelist[@automationid='TabControl']/tabpage[@index='0']/container[1]/container/container[1]/container[1]/text[2]", 30000, null, "20c57de7-bf1e-40b2-a357-fa70771b6271");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "container[2]/tabpagelist[@automationid='TabControl']/tabpage[@index='0']/container[1]/container/container[2]", 30000, null, "36af43d8-d57b-4e80-bad2-98ee195d076f");
                _ribbonInfo = new RepoItemInfo(this, "Ribbon", "list[@automationid='Ribbon']", 30000, null, "840562c3-c6b4-4da3-a39b-2dce46e89651");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aceaf7d9-8edb-49b8-877d-364e99925502")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aceaf7d9-8edb-49b8-877d-364e99925502")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("20c57de7-bf1e-40b2-a357-fa70771b6271")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("20c57de7-bf1e-40b2-a357-fa70771b6271")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("36af43d8-d57b-4e80-bad2-98ee195d076f")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("36af43d8-d57b-4e80-bad2-98ee195d076f")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The Ribbon item.
            /// </summary>
            [RepositoryItem("840562c3-c6b4-4da3-a39b-2dce46e89651")]
            public virtual Ranorex.List Ribbon
            {
                get
                {
                    return _ribbonInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Ribbon item info.
            /// </summary>
            [RepositoryItemInfo("840562c3-c6b4-4da3-a39b-2dce46e89651")]
            public virtual RepoItemInfo RibbonInfo
            {
                get
                {
                    return _ribbonInfo;
                }
            }
        }

        /// <summary>
        /// The NewProtocolWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("2919cf15-927b-4a31-99f3-f4f743525167")]
        public partial class NewProtocolWizardAppFolder : RepoGenBaseFolder
        {
            MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder _somecontainer2;
            RepoItemInfo _copy_of_indeterminatemarkInfo;
            RepoItemInfo _somecontainer1Info;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _закритиInfo;

            /// <summary>
            /// Creates a new NewProtocolWizard  folder.
            /// </summary>
            public NewProtocolWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewProtocolWizard", "/form[@wpfnative='True' and @title='New Protocol Wizard' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 30000, null, true, "2919cf15-927b-4a31-99f3-f4f743525167", "")
            {
                _somecontainer2 = new MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder(this);
                _copy_of_indeterminatemarkInfo = new RepoItemInfo(this, "Copy_of_IndeterminateMark", "element/container/element/container/container/container/checkbox[@text='Launch protocol']", 30000, null, "540e1b9e-15e4-4641-9939-cefea693a796");
                _somecontainer1Info = new RepoItemInfo(this, "SomeContainer1", ".//container[@automationid='Self']//list[@automationid='MainListBox']/container/listitem[1]/container/container/container[@automationid='ImageGrid']/container", 30000, null, "22ab5f3a-d1f3-48fa-9c56-4c94dbedc56d");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "element//container[@automationid='Self']/container/container/container/list[@automationid='CreateDropDownButton']/?/?/checkbox[@automationid='ToggleButton']/container", 30000, null, "264eeeb6-dc23-474a-a7d9-35d601f2bc52");
                _закритиInfo = new RepoItemInfo(this, "Закрити", "?/?/button[@accessiblename='Закрити']", 30000, null, "abd25614-2d26-47c5-8434-a260ef8194c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2919cf15-927b-4a31-99f3-f4f743525167")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2919cf15-927b-4a31-99f3-f4f743525167")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Copy_of_IndeterminateMark item.
            /// </summary>
            [RepositoryItem("540e1b9e-15e4-4641-9939-cefea693a796")]
            public virtual Ranorex.CheckBox Copy_of_IndeterminateMark
            {
                get
                {
                    return _copy_of_indeterminatemarkInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Copy_of_IndeterminateMark item info.
            /// </summary>
            [RepositoryItemInfo("540e1b9e-15e4-4641-9939-cefea693a796")]
            public virtual RepoItemInfo Copy_of_IndeterminateMarkInfo
            {
                get
                {
                    return _copy_of_indeterminatemarkInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 item.
            /// </summary>
            [RepositoryItem("22ab5f3a-d1f3-48fa-9c56-4c94dbedc56d")]
            public virtual Ranorex.Container SomeContainer1
            {
                get
                {
                    return _somecontainer1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer1 item info.
            /// </summary>
            [RepositoryItemInfo("22ab5f3a-d1f3-48fa-9c56-4c94dbedc56d")]
            public virtual RepoItemInfo SomeContainer1Info
            {
                get
                {
                    return _somecontainer1Info;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("264eeeb6-dc23-474a-a7d9-35d601f2bc52")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("264eeeb6-dc23-474a-a7d9-35d601f2bc52")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The Закрити item.
            /// </summary>
            [RepositoryItem("abd25614-2d26-47c5-8434-a260ef8194c2")]
            public virtual Ranorex.Button Закрити
            {
                get
                {
                    return _закритиInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрити item info.
            /// </summary>
            [RepositoryItemInfo("abd25614-2d26-47c5-8434-a260ef8194c2")]
            public virtual RepoItemInfo ЗакритиInfo
            {
                get
                {
                    return _закритиInfo;
                }
            }

            /// <summary>
            /// The SomeContainer2 folder.
            /// </summary>
            [RepositoryFolder("5fc0a55c-2026-46c4-b6ec-c14e1c56332b")]
            public virtual MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder SomeContainer2
            {
                get { return _somecontainer2; }
            }
        }

        /// <summary>
        /// The SomeContainer2Folder folder.
        /// </summary>
        [RepositoryFolder("5fc0a55c-2026-46c4-b6ec-c14e1c56332b")]
        public partial class SomeContainer2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _finishInfo;
            RepoItemInfo _nextInfo;
            RepoItemInfo _advancedviewbuttonInfo;
            RepoItemInfo _somelist2Info;
            RepoItemInfo _reviewtheconfigurationsummarypressInfo;
            RepoItemInfo _optionmarkInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _somelistInfo;
            RepoItemInfo _somelist1Info;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _nameyourprotocolandoptionallyprovidInfo;
            RepoItemInfo _selectthesampletypesusedinyourassInfo;
            RepoItemInfo _launchprotocolInfo;
            RepoItemInfo _indeterminatemarkInfo;

            /// <summary>
            /// Creates a new SomeContainer2  folder.
            /// </summary>
            public SomeContainer2Folder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer2", "element/container", parentFolder, 30000, null, false, "5fc0a55c-2026-46c4-b6ec-c14e1c56332b", "")
            {
                _finishInfo = new RepoItemInfo(this, "Finish", ".//button[@text='Finish']", 30000, null, "73a1471f-7bf3-47e3-bc41-1fb41b69eef3");
                _nextInfo = new RepoItemInfo(this, "Next", ".///button[@text='Next']", 30000, null, "d61b0b04-cec4-4a86-8e0a-a00721dcf0c8");
                _advancedviewbuttonInfo = new RepoItemInfo(this, "AdvancedViewButton", ".///button[@automationid='AdvancedViewButton']", 30000, null, "4787ed15-ab23-4e0b-ac28-642037da65a8");
                _somelist2Info = new RepoItemInfo(this, "SomeList2", "element/container/container/container/list", 30000, null, "08ffd434-f205-40d3-a1ff-bbfa459e7070");
                _reviewtheconfigurationsummarypressInfo = new RepoItemInfo(this, "ReviewTheConfigurationSummaryPress", "element/container/container/container/text[@caption~'^Review\\ the\\ configuration\\ ']", 30000, null, "01842733-a381-4522-8666-0f7d8d7a358d");
                _optionmarkInfo = new RepoItemInfo(this, "OptionMark", ".//radiobutton[@text~'^I\\ will\\ enter/paste\\ in\\ my\\ ']/element[@automationid='optionMark']", 30000, null, "505f0a97-8fcb-4246-810f-19158b71caf0");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "element/container/container/container[2]", 30000, null, "971c7e66-c7f0-4549-906b-38d2c25356d3");
                _somelistInfo = new RepoItemInfo(this, "SomeList", "element/container/container/list[1]", 30000, null, "1b61e45c-bc22-4c05-b09f-c9182c7609ca");
                _somelist1Info = new RepoItemInfo(this, "SomeList1", "element/container/container/list[2]", 30000, null, "9b92f8dd-c01a-4122-a5f7-73b7ff946385");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element/container/container/text[@caption='']/element[2]", 30000, null, "8b7b91ea-bee6-49b6-a66a-56425c1caa88");
                _nameyourprotocolandoptionallyprovidInfo = new RepoItemInfo(this, "NameYourProtocolAndOptionallyProvid", "element/container/container/text[@caption~'^Name\\ your\\ protocol\\ and\\ op']", 30000, null, "e407e38d-ebb3-42f5-b24f-a9afa853d012");
                _selectthesampletypesusedinyourassInfo = new RepoItemInfo(this, "SelectTheSampleTypesUsedInYourAss", "element/container/container/text[@caption~'^Select\\ the\\ sample\\ types\\ u']", 30000, null, "1830f6a9-9a4a-4631-bcf7-c2da40f54106");
                _launchprotocolInfo = new RepoItemInfo(this, "LaunchProtocol", ".//checkbox[@text='Launch protocol']", 30000, null, "07a6b546-cbf7-4b62-804f-9af4d24719ab");
                _indeterminatemarkInfo = new RepoItemInfo(this, "IndeterminateMark", "element/container/container/container/checkbox[@text='Launch protocol']/container[@automationid='markGrid']/element[@automationid='indeterminateMark']", 30000, null, "1507336f-6aff-48df-b90f-b5778cf156cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5fc0a55c-2026-46c4-b6ec-c14e1c56332b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5fc0a55c-2026-46c4-b6ec-c14e1c56332b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("73a1471f-7bf3-47e3-bc41-1fb41b69eef3")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("73a1471f-7bf3-47e3-bc41-1fb41b69eef3")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("d61b0b04-cec4-4a86-8e0a-a00721dcf0c8")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("d61b0b04-cec4-4a86-8e0a-a00721dcf0c8")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The AdvancedViewButton item.
            /// </summary>
            [RepositoryItem("4787ed15-ab23-4e0b-ac28-642037da65a8")]
            public virtual Ranorex.Button AdvancedViewButton
            {
                get
                {
                    return _advancedviewbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AdvancedViewButton item info.
            /// </summary>
            [RepositoryItemInfo("4787ed15-ab23-4e0b-ac28-642037da65a8")]
            public virtual RepoItemInfo AdvancedViewButtonInfo
            {
                get
                {
                    return _advancedviewbuttonInfo;
                }
            }

            /// <summary>
            /// The SomeList2 item.
            /// </summary>
            [RepositoryItem("08ffd434-f205-40d3-a1ff-bbfa459e7070")]
            public virtual Ranorex.List SomeList2
            {
                get
                {
                    return _somelist2Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList2 item info.
            /// </summary>
            [RepositoryItemInfo("08ffd434-f205-40d3-a1ff-bbfa459e7070")]
            public virtual RepoItemInfo SomeList2Info
            {
                get
                {
                    return _somelist2Info;
                }
            }

            /// <summary>
            /// The ReviewTheConfigurationSummaryPress item.
            /// </summary>
            [RepositoryItem("01842733-a381-4522-8666-0f7d8d7a358d")]
            public virtual Ranorex.Text ReviewTheConfigurationSummaryPress
            {
                get
                {
                    return _reviewtheconfigurationsummarypressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ReviewTheConfigurationSummaryPress item info.
            /// </summary>
            [RepositoryItemInfo("01842733-a381-4522-8666-0f7d8d7a358d")]
            public virtual RepoItemInfo ReviewTheConfigurationSummaryPressInfo
            {
                get
                {
                    return _reviewtheconfigurationsummarypressInfo;
                }
            }

            /// <summary>
            /// The OptionMark item.
            /// </summary>
            [RepositoryItem("505f0a97-8fcb-4246-810f-19158b71caf0")]
            public virtual Ranorex.Unknown OptionMark
            {
                get
                {
                    return _optionmarkInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The OptionMark item info.
            /// </summary>
            [RepositoryItemInfo("505f0a97-8fcb-4246-810f-19158b71caf0")]
            public virtual RepoItemInfo OptionMarkInfo
            {
                get
                {
                    return _optionmarkInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("971c7e66-c7f0-4549-906b-38d2c25356d3")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("971c7e66-c7f0-4549-906b-38d2c25356d3")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The SomeList item.
            /// </summary>
            [RepositoryItem("1b61e45c-bc22-4c05-b09f-c9182c7609ca")]
            public virtual Ranorex.List SomeList
            {
                get
                {
                    return _somelistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList item info.
            /// </summary>
            [RepositoryItemInfo("1b61e45c-bc22-4c05-b09f-c9182c7609ca")]
            public virtual RepoItemInfo SomeListInfo
            {
                get
                {
                    return _somelistInfo;
                }
            }

            /// <summary>
            /// The SomeList1 item.
            /// </summary>
            [RepositoryItem("9b92f8dd-c01a-4122-a5f7-73b7ff946385")]
            public virtual Ranorex.List SomeList1
            {
                get
                {
                    return _somelist1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList1 item info.
            /// </summary>
            [RepositoryItemInfo("9b92f8dd-c01a-4122-a5f7-73b7ff946385")]
            public virtual RepoItemInfo SomeList1Info
            {
                get
                {
                    return _somelist1Info;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("8b7b91ea-bee6-49b6-a66a-56425c1caa88")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("8b7b91ea-bee6-49b6-a66a-56425c1caa88")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The NameYourProtocolAndOptionallyProvid item.
            /// </summary>
            [RepositoryItem("e407e38d-ebb3-42f5-b24f-a9afa853d012")]
            public virtual Ranorex.Text NameYourProtocolAndOptionallyProvid
            {
                get
                {
                    return _nameyourprotocolandoptionallyprovidInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NameYourProtocolAndOptionallyProvid item info.
            /// </summary>
            [RepositoryItemInfo("e407e38d-ebb3-42f5-b24f-a9afa853d012")]
            public virtual RepoItemInfo NameYourProtocolAndOptionallyProvidInfo
            {
                get
                {
                    return _nameyourprotocolandoptionallyprovidInfo;
                }
            }

            /// <summary>
            /// The SelectTheSampleTypesUsedInYourAss item.
            /// </summary>
            [RepositoryItem("1830f6a9-9a4a-4631-bcf7-c2da40f54106")]
            public virtual Ranorex.Text SelectTheSampleTypesUsedInYourAss
            {
                get
                {
                    return _selectthesampletypesusedinyourassInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SelectTheSampleTypesUsedInYourAss item info.
            /// </summary>
            [RepositoryItemInfo("1830f6a9-9a4a-4631-bcf7-c2da40f54106")]
            public virtual RepoItemInfo SelectTheSampleTypesUsedInYourAssInfo
            {
                get
                {
                    return _selectthesampletypesusedinyourassInfo;
                }
            }

            /// <summary>
            /// The LaunchProtocol item.
            /// </summary>
            [RepositoryItem("07a6b546-cbf7-4b62-804f-9af4d24719ab")]
            public virtual Ranorex.CheckBox LaunchProtocol
            {
                get
                {
                    return _launchprotocolInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The LaunchProtocol item info.
            /// </summary>
            [RepositoryItemInfo("07a6b546-cbf7-4b62-804f-9af4d24719ab")]
            public virtual RepoItemInfo LaunchProtocolInfo
            {
                get
                {
                    return _launchprotocolInfo;
                }
            }

            /// <summary>
            /// The IndeterminateMark item.
            /// </summary>
            [RepositoryItem("1507336f-6aff-48df-b90f-b5778cf156cc")]
            public virtual Ranorex.Unknown IndeterminateMark
            {
                get
                {
                    return _indeterminatemarkInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IndeterminateMark item info.
            /// </summary>
            [RepositoryItemInfo("1507336f-6aff-48df-b90f-b5778cf156cc")]
            public virtual RepoItemInfo IndeterminateMarkInfo
            {
                get
                {
                    return _indeterminatemarkInfo;
                }
            }
        }

        /// <summary>
        /// The SampleTypesEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("73c552ed-057f-4e5d-b263-ea1a497edb57")]
        public partial class SampleTypesEditorAppFolder : RepoGenBaseFolder
        {
            MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder1 _somecontainer2;
            RepoItemInfo _togglebuttonInfo;
            RepoItemInfo _somecontainer1Info;

            /// <summary>
            /// Creates a new SampleTypesEditor  folder.
            /// </summary>
            public SampleTypesEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleTypesEditor", "/form[@wpfnative='True' and @title='Sample Types Editor' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 30000, null, true, "73c552ed-057f-4e5d-b263-ea1a497edb57", "")
            {
                _somecontainer2 = new MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder1(this);
                _togglebuttonInfo = new RepoItemInfo(this, "ToggleButton", ".//list[@automationid='SampleTypesSimplifiedView']/container/container[9]/?/?/combobox/container[@automationid='templateRoot']/checkbox[@automationid='toggleButton']", 30000, null, "2be10c16-688c-4587-995a-463ec1a64de6");
                _somecontainer1Info = new RepoItemInfo(this, "SomeContainer1", "container", 30000, null, "eb20e9e8-9ca6-4d43-b1a7-b7f462792d4d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73c552ed-057f-4e5d-b263-ea1a497edb57")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73c552ed-057f-4e5d-b263-ea1a497edb57")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToggleButton item.
            /// </summary>
            [RepositoryItem("2be10c16-688c-4587-995a-463ec1a64de6")]
            public virtual Ranorex.CheckBox ToggleButton
            {
                get
                {
                    return _togglebuttonInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ToggleButton item info.
            /// </summary>
            [RepositoryItemInfo("2be10c16-688c-4587-995a-463ec1a64de6")]
            public virtual RepoItemInfo ToggleButtonInfo
            {
                get
                {
                    return _togglebuttonInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 item.
            /// </summary>
            [RepositoryItem("eb20e9e8-9ca6-4d43-b1a7-b7f462792d4d")]
            public virtual Ranorex.Container SomeContainer1
            {
                get
                {
                    return _somecontainer1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer1 item info.
            /// </summary>
            [RepositoryItemInfo("eb20e9e8-9ca6-4d43-b1a7-b7f462792d4d")]
            public virtual RepoItemInfo SomeContainer1Info
            {
                get
                {
                    return _somecontainer1Info;
                }
            }

            /// <summary>
            /// The SomeContainer2 folder.
            /// </summary>
            [RepositoryFolder("f6778bdd-bfdb-4734-aacd-04fbde037357")]
            public virtual MyAssaysDesktopExplorerRepositoryFolders.SomeContainer2Folder1 SomeContainer2
            {
                get { return _somecontainer2; }
            }
        }

        /// <summary>
        /// The SomeContainer2Folder1 folder.
        /// </summary>
        [RepositoryFolder("f6778bdd-bfdb-4734-aacd-04fbde037357")]
        public partial class SomeContainer2Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _addsampletypeInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _editthesampletypesusedinyourassayInfo;
            RepoItemInfo _someelement1Info;

            /// <summary>
            /// Creates a new SomeContainer2  folder.
            /// </summary>
            public SomeContainer2Folder1(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer2", "container", parentFolder, 30000, null, false, "f6778bdd-bfdb-4734-aacd-04fbde037357", "")
            {
                _addsampletypeInfo = new RepoItemInfo(this, "AddSampleType", ".//button[@text='Add Sample Type']", 30000, null, "c712f50b-438a-4d67-86b7-58ff91818881");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//button[@text='OK']", 30000, null, "1bd27730-a830-422f-9ce4-1df68e6c396e");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "?/?/list[@automationid='SampleTypesSimplifiedView']/container/container[9]//checkbox[@automationid='colorToggleButton']/container", 30000, null, "3870c2aa-ef76-4b06-b4c2-1cb19fb4f3b2");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "?/?/list[@automationid='SampleTypesSimplifiedView']/container/container[9]/text/element[2]", 30000, null, "40647534-d940-46ae-8536-97894bbd7d41");
                _editthesampletypesusedinyourassayInfo = new RepoItemInfo(this, "EditTheSampleTypesUsedInYourAssay", "?/?/text[@caption~'^Edit\\ the\\ sample\\ types\\ use']", 30000, null, "13b2f154-3460-4602-bc75-f649bf82dd23");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "?/?/list[@automationid='SampleTypesSimplifiedView']/container/container[10]/text/element[2]", 30000, null, "48cb36e0-a1a9-4411-8c31-64373674f37c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6778bdd-bfdb-4734-aacd-04fbde037357")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6778bdd-bfdb-4734-aacd-04fbde037357")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddSampleType item.
            /// </summary>
            [RepositoryItem("c712f50b-438a-4d67-86b7-58ff91818881")]
            public virtual Ranorex.Button AddSampleType
            {
                get
                {
                    return _addsampletypeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddSampleType item info.
            /// </summary>
            [RepositoryItemInfo("c712f50b-438a-4d67-86b7-58ff91818881")]
            public virtual RepoItemInfo AddSampleTypeInfo
            {
                get
                {
                    return _addsampletypeInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("1bd27730-a830-422f-9ce4-1df68e6c396e")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("1bd27730-a830-422f-9ce4-1df68e6c396e")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("3870c2aa-ef76-4b06-b4c2-1cb19fb4f3b2")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("3870c2aa-ef76-4b06-b4c2-1cb19fb4f3b2")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("40647534-d940-46ae-8536-97894bbd7d41")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("40647534-d940-46ae-8536-97894bbd7d41")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The EditTheSampleTypesUsedInYourAssay item.
            /// </summary>
            [RepositoryItem("13b2f154-3460-4602-bc75-f649bf82dd23")]
            public virtual Ranorex.Text EditTheSampleTypesUsedInYourAssay
            {
                get
                {
                    return _editthesampletypesusedinyourassayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditTheSampleTypesUsedInYourAssay item info.
            /// </summary>
            [RepositoryItemInfo("13b2f154-3460-4602-bc75-f649bf82dd23")]
            public virtual RepoItemInfo EditTheSampleTypesUsedInYourAssayInfo
            {
                get
                {
                    return _editthesampletypesusedinyourassayInfo;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("48cb36e0-a1a9-4411-8c31-64373674f37c")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("48cb36e0-a1a9-4411-8c31-64373674f37c")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }
        }

        /// <summary>
        /// The MyAssaysDesktopExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ad59ab9-a199-46e3-99d6-597e5ab45eae")]
        public partial class MyAssaysDesktopExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _calibratorInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _listviewInfo;

            /// <summary>
            /// Creates a new MyAssaysDesktopExplorer  folder.
            /// </summary>
            public MyAssaysDesktopExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyAssaysDesktopExplorer", "/contextmenu[@processname='MyAssays.Desktop.Explorer' and @win32ownerwindowlevel='1']", parentFolder, 30000, null, false, "7ad59ab9-a199-46e3-99d6-597e5ab45eae", "")
            {
                _calibratorInfo = new RepoItemInfo(this, "Calibrator", "listitem[@text='Calibrator']", 30000, null, "859c605f-2aad-44de-a07e-13491fcdb9f6");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "element[@automationid='ColorEdit']/container/container[1]", 30000, null, "79d61f3d-9bc3-4105-b419-cd1daefed7d2");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "element[@automationid='ColorEdit']//slider[@automationid='PART_Track']/button[1]", 30000, null, "1eb8c5bf-73a5-4557-904c-31e1bb2192d0");
                _listviewInfo = new RepoItemInfo(this, "ListView", "list[@automationid='ListView']", 30000, null, "4e89b8ba-3480-4065-94e1-7049cfbb49e6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ad59ab9-a199-46e3-99d6-597e5ab45eae")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ad59ab9-a199-46e3-99d6-597e5ab45eae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Calibrator item.
            /// </summary>
            [RepositoryItem("859c605f-2aad-44de-a07e-13491fcdb9f6")]
            public virtual Ranorex.ListItem Calibrator
            {
                get
                {
                    return _calibratorInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Calibrator item info.
            /// </summary>
            [RepositoryItemInfo("859c605f-2aad-44de-a07e-13491fcdb9f6")]
            public virtual RepoItemInfo CalibratorInfo
            {
                get
                {
                    return _calibratorInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("79d61f3d-9bc3-4105-b419-cd1daefed7d2")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("79d61f3d-9bc3-4105-b419-cd1daefed7d2")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("1eb8c5bf-73a5-4557-904c-31e1bb2192d0")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("1eb8c5bf-73a5-4557-904c-31e1bb2192d0")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The ListView item.
            /// </summary>
            [RepositoryItem("4e89b8ba-3480-4065-94e1-7049cfbb49e6")]
            public virtual Ranorex.List ListView
            {
                get
                {
                    return _listviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ListView item info.
            /// </summary>
            [RepositoryItemInfo("4e89b8ba-3480-4065-94e1-7049cfbb49e6")]
            public virtual RepoItemInfo ListViewInfo
            {
                get
                {
                    return _listviewInfo;
                }
            }
        }

        /// <summary>
        /// The LayoutEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("03f04b93-4edc-41a9-9a2e-753335eeaa1f")]
        public partial class LayoutEditorAppFolder : RepoGenBaseFolder
        {
            MyAssaysDesktopExplorerRepositoryFolders.PARTElementPlateGridFolder _partelementplategrid;
            RepoItemInfo _partimageInfo;

            /// <summary>
            /// Creates a new LayoutEditor  folder.
            /// </summary>
            public LayoutEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LayoutEditor", "/form[@wpfnative='True' and @title='Layout Editor' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 30000, null, true, "03f04b93-4edc-41a9-9a2e-753335eeaa1f", "")
            {
                _partelementplategrid = new MyAssaysDesktopExplorerRepositoryFolders.PARTElementPlateGridFolder(this);
                _partimageInfo = new RepoItemInfo(this, "PARTImage", "element[@automationid='MainLayoutEditor']/container/container[3]/list/?/?/list[@automationid='ChildBlock']//picture[@automationid='PART_Image']", 30000, null, "339b62de-8c96-47d6-bd81-d8d44ae2ff2d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03f04b93-4edc-41a9-9a2e-753335eeaa1f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03f04b93-4edc-41a9-9a2e-753335eeaa1f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTImage item.
            /// </summary>
            [RepositoryItem("339b62de-8c96-47d6-bd81-d8d44ae2ff2d")]
            public virtual Ranorex.Picture PARTImage
            {
                get
                {
                    return _partimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PARTImage item info.
            /// </summary>
            [RepositoryItemInfo("339b62de-8c96-47d6-bd81-d8d44ae2ff2d")]
            public virtual RepoItemInfo PARTImageInfo
            {
                get
                {
                    return _partimageInfo;
                }
            }

            /// <summary>
            /// The PARTElementPlateGrid folder.
            /// </summary>
            [RepositoryFolder("bfe6622c-91ae-4eda-9144-7c4fc05ea9f2")]
            public virtual MyAssaysDesktopExplorerRepositoryFolders.PARTElementPlateGridFolder PARTElementPlateGrid
            {
                get { return _partelementplategrid; }
            }
        }

        /// <summary>
        /// The PARTElementPlateGridFolder folder.
        /// </summary>
        [RepositoryFolder("bfe6622c-91ae-4eda-9144-7c4fc05ea9f2")]
        public partial class PARTElementPlateGridFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mainrectInfo;
            RepoItemInfo _text12Info;
            RepoItemInfo _text13Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _text3Info;
            RepoItemInfo _text5Info;

            /// <summary>
            /// Creates a new PARTElementPlateGrid  folder.
            /// </summary>
            public PARTElementPlateGridFolder(RepoGenBaseFolder parentFolder) :
                    base("PARTElementPlateGrid", ".//container[@automationid='PART_ElementPlateGrid']", parentFolder, 30000, null, false, "bfe6622c-91ae-4eda-9144-7c4fc05ea9f2", "")
            {
                _mainrectInfo = new RepoItemInfo(this, "MAINRECT", "element[@automationid='PART_ElementLayoutGrid']/?/?/element[@automationid='MAIN_RECT']", 30000, null, "dcb8189f-1d6e-44f4-b054-34f177a77f96");
                _text12Info = new RepoItemInfo(this, "TEXT12", "element[@automationid='PART_ElementLayoutGrid']/container[@automationid='RootCanvas']/?/?/text[@automationid='TEXT_12']", 30000, null, "716a4803-79e1-4655-b666-3f4c621d9b65");
                _text13Info = new RepoItemInfo(this, "TEXT13", "element[@automationid='PART_ElementLayoutGrid']/container[@automationid='RootCanvas']/?/?/text[@automationid='TEXT_13']", 30000, null, "3da90b6a-8227-4fe8-9a6d-6180d58d96c0");
                _text2Info = new RepoItemInfo(this, "TEXT2", "element[@automationid='PART_ElementLayoutGrid']/container[@automationid='RootCanvas']/?/?/text[@automationid='TEXT_2']", 30000, null, "971ffc4d-785e-4687-9146-ec5fded39710");
                _text3Info = new RepoItemInfo(this, "TEXT3", "element[@automationid='PART_ElementLayoutGrid']/container[@automationid='RootCanvas']/?/?/text[@automationid='TEXT_3']", 30000, null, "5bb7e807-2e5e-4844-a1c4-9717445eb0c5");
                _text5Info = new RepoItemInfo(this, "TEXT5", "element[@automationid='PART_ElementLayoutGrid']/container[@automationid='RootCanvas']/?/?/text[@automationid='TEXT_5']", 30000, null, "09e59c49-0126-4d63-9afe-a78a4e605f24");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bfe6622c-91ae-4eda-9144-7c4fc05ea9f2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bfe6622c-91ae-4eda-9144-7c4fc05ea9f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MAINRECT item.
            /// </summary>
            [RepositoryItem("dcb8189f-1d6e-44f4-b054-34f177a77f96")]
            public virtual Ranorex.Unknown MAINRECT
            {
                get
                {
                    return _mainrectInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MAINRECT item info.
            /// </summary>
            [RepositoryItemInfo("dcb8189f-1d6e-44f4-b054-34f177a77f96")]
            public virtual RepoItemInfo MAINRECTInfo
            {
                get
                {
                    return _mainrectInfo;
                }
            }

            /// <summary>
            /// The TEXT12 item.
            /// </summary>
            [RepositoryItem("716a4803-79e1-4655-b666-3f4c621d9b65")]
            public virtual Ranorex.Text TEXT12
            {
                get
                {
                    return _text12Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEXT12 item info.
            /// </summary>
            [RepositoryItemInfo("716a4803-79e1-4655-b666-3f4c621d9b65")]
            public virtual RepoItemInfo TEXT12Info
            {
                get
                {
                    return _text12Info;
                }
            }

            /// <summary>
            /// The TEXT13 item.
            /// </summary>
            [RepositoryItem("3da90b6a-8227-4fe8-9a6d-6180d58d96c0")]
            public virtual Ranorex.Text TEXT13
            {
                get
                {
                    return _text13Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEXT13 item info.
            /// </summary>
            [RepositoryItemInfo("3da90b6a-8227-4fe8-9a6d-6180d58d96c0")]
            public virtual RepoItemInfo TEXT13Info
            {
                get
                {
                    return _text13Info;
                }
            }

            /// <summary>
            /// The TEXT2 item.
            /// </summary>
            [RepositoryItem("971ffc4d-785e-4687-9146-ec5fded39710")]
            public virtual Ranorex.Text TEXT2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEXT2 item info.
            /// </summary>
            [RepositoryItemInfo("971ffc4d-785e-4687-9146-ec5fded39710")]
            public virtual RepoItemInfo TEXT2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The TEXT3 item.
            /// </summary>
            [RepositoryItem("5bb7e807-2e5e-4844-a1c4-9717445eb0c5")]
            public virtual Ranorex.Text TEXT3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEXT3 item info.
            /// </summary>
            [RepositoryItemInfo("5bb7e807-2e5e-4844-a1c4-9717445eb0c5")]
            public virtual RepoItemInfo TEXT3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The TEXT5 item.
            /// </summary>
            [RepositoryItem("09e59c49-0126-4d63-9afe-a78a4e605f24")]
            public virtual Ranorex.Text TEXT5
            {
                get
                {
                    return _text5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEXT5 item info.
            /// </summary>
            [RepositoryItemInfo("09e59c49-0126-4d63-9afe-a78a4e605f24")]
            public virtual RepoItemInfo TEXT5Info
            {
                get
                {
                    return _text5Info;
                }
            }
        }

    }
#pragma warning restore 0436
}